# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    time: 08:00:00 # time limit for each job
    cpus-per-task: 2
    mem: 16G
    output: results/logs/slurm-%x.%A.%a.log

fastqc_reads:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

fastq_screen:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

align_with_bowtie2:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

sam_to_bam:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

sort_bam:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

index_bam:
    cpus-per-task: 2
    mem: 16G
    cores: 2
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_bigwig_raw:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

calculate_total_reads:
    cpus-per-task: 2
    mem: 16G
    cores: 2
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_bigwig_scaled:
    cpus-per-task: 4
    mem: 32G
    cores: 4
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

macs2_peak_calling:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err
