# Bowtie2 genome index path
bowtie2_genome: "/hpc-prj/kirkland/shared/scripts/mm10_bowtie2_index/mm10"

# bamCoverage parameters for BigWig generation
bin_size: 10000
min_mapping_quality: 30
effective_genome_size: 2730871774  # mm10 genome size

# EnvModules
fastqc: "fastqc/0.12.1"
fastq_screen: "fastq_screen/0.14.0"
samtools: "samtools/1.18"
bowtie2: "bowtie2/2.4.5"
deeptools: "deeptools/3.4.3"
